[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

lib_deps =
    https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary.git
    mikalhart/TinyGPSPlus @ ^1.0.3
    https://github.com/jarzebski/Arduino-MS5611.git
